logging:
  level:
    io:
      pivotal: DEBUG
eureka: # <--- ADD NEW SECTION
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}

---

spring:
  profiles: cloud
eureka:
  client:    
    serviceUrl:
      defaultZone:http://service-registry-orinasal-binocle.run.aws-usw02-pr.ice.predix.io/eureka
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id}

---

spring:
  profiles: dev
eureka:
  client:    
    serviceUrl:
      defaultZone: service-registry-orinasal-binocle.run.aws-usw02-pr.ice.predix.io/eureka/ 
